baseURL: "https://wahbakamaluddin.github.io/"
title: wahba
pagination:
  papersize: 5
theme: [PaperMod]

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        # - name: WiKi
        #   url: https://github.com/adityatelange/hugo-PaperMod/wiki/
    params:
      homeInfoParams:
        Title: "print('hi')"
        Content: >
          I'm sharing various CS topics that might come in handy for students, including notes from my foundation to undergraduate studies, CTF writeups, and other interesting finds. Hope it helps!
      socialIcons:
        - name: github
          title: check out my GitHub
          url: "https://github.com/wahbakamaluddin"
        - name: "youtube"
          title: Check out my youtube channel
          url: "https://www.youtube.com/@wahbakamaluddin"
        - name: "linkedin"
          title: Check out my linkedin
          url: "https://www.linkedin.com/in/wahbakamaluddin/"
      # ShowShareButtons: true
      ShowCodeCopyButtons: true
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    codeFences: true
    lineNos: true
    style: monokai
