baseURL: "https://wahbakamaluddin.github.io/"
title: wahba
paginate: 5
theme: [PaperMod]

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        # - name: WiKi
        #   url: https://github.com/adityatelange/hugo-PaperMod/wiki/
    params:
      homeInfoParams:
        Title: "hi"
        Content: >
          Just sharing cool computer science stuff that might come in handy for students—notes, writeups, and random finds. Hope it helps!
          -- STILL UNDER CONSTRUCTION --
      socialIcons:
        - name: github
          title: check out my GitHub
          url: "https://github.com/wahbakamaluddin"
        - name: "youtube"
          title: Check out my youtube channel
          url: "https://www.youtube.com/@wahbakamaluddin"
        - name: "linkedin"
          title: Check out my linkedin
          url: "https://www.linkedin.com/in/wahbakamaluddin/"
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
